### ISSUE TITLE
Object Reference is Not an Object

### ISSUE THREAD

**Issue by jaycosentino** [Azure/Azure-Media-Services-Explorer#115] opened 2019-07-19 17:37 UTC
I have been using the Azure Media Services Explorer for years without issue.  Now, I am having an issue.  I can connect to the account, but I get the below Unhandled Exception window where I click on Continue.  I had been getting this lately, but pressing continue allowed me to do what I needed (view the main assets window, batch uploads, publish locators, download excel info, etc.).  Today, I am getting the new Connecting window.  I go to do a batch upload: I select the directory without issue, then get the “Connecting” window which never goes away.  

I have tried from two different computers (one is Win 7 and one is Win 10) with the same result.  

Below are the two windows displays and the list of the details from the unhandled exception.

I am able to ignore these message and do my work.  I do not know if there is a problem in my account, my computers, or your software.

Jay

Jay Cosentino
Computer Analytics
999 E. Touhy Ave. Ste 130
Des Plaines, IL  60018
jcosentino@cacorp.com

 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.MediaServices.Client.PresentationTimeRange..ctor(PresentationTimeRangeData data)
   at Microsoft.WindowsAzure.MediaServices.Client.StreamingFilterData.Microsoft.WindowsAzure.MediaServices.Client.IStreamingFilter.get_PresentationTimeRange()
   at AMSExplorer.Mainform.DoRefreshGridFiltersV(Boolean firstime)
   at AMSExplorer.Mainform.Mainform_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AMSExplorer
    Assembly Version: 4.3.5.0
    Win32 Version: 4.3.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/AMSExplorer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.WindowsAzure.MediaServices.Client
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.MediaServices.Client.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3429.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
Microsoft.Rest.ClientRuntime.Azure.Authentication
    Assembly Version: 2.0.0.0
    Win32 Version: 2.3.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Rest.ClientRuntime.Azure.Authentication.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3440.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.WindowsAzure.MediaServices.Client.Common.Authentication
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.MediaServices.Client.Common.Authentication.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 3.19.8.16603
    Win32 Version: 3.19.50615.2240
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.Data.Services.Client
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Data.Services.Client.DLL
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Microsoft.Practices.TransientFaultHandling.Core
    Assembly Version: 5.1.1209.0
    Win32 Version: 5.1.1209.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Practices.TransientFaultHandling.Core.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3440.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3440.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Microsoft.Data.Edm
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Data.Edm.DLL
----------------------------------------
Microsoft.Data.OData
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Data.OData.DLL
----------------------------------------
System.Spatial
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/System.Spatial.DLL
----------------------------------------
Microsoft.WindowsAzure.Storage
    Assembly Version: 9.3.2.0
    Win32 Version: 9.3.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.Storage.DLL
----------------------------------------
Microsoft.Azure.Management.Media
    Assembly Version: 0.1.0.0
    Win32 Version: 0.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Azure.Management.Media.DLL
----------------------------------------
Microsoft.Rest.ClientRuntime
    Assembly Version: 2.0.0.0
    Win32 Version: 2.3.18.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Rest.ClientRuntime.DLL
----------------------------------------
Microsoft.Rest.ClientRuntime.Azure
    Assembly Version: 3.0.0.0
    Win32 Version: 3.3.18.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Rest.ClientRuntime.Azure.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.Azure.KeyVault.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Azure.KeyVault.Core.DLL
----------------------------------------
Microsoft.WindowsAzure.MediaServices.Client.Extensions
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.MediaServices.Client.Extensions.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by xpouyat** [comment] 2019-07-19 17:42
Hello Jay,
The issue seems related to a filter (global filter I think).
Did you create recently a filter with AMSE or with some code ?
- Xavier

**Comment by jaycosentino** [comment] 2019-07-19 19:35
Thanks!  I am using a quite vanilla version of the AMSE.  No programming by us and no global filters if that is what you are referring to.  Global filter tab is empty. Nothing different than what I have used in the past.


1.       I start normally.

2.       Before displaying my assets, it comes up with the unhandled exception. (picture 1)

3.       Click on continue and the software runs normally.

4.       The Connecting to the Media Services account – arclearn (picture 2) continues to display but I can ignore it.

5.       My Asset screen shows up.  (picture 3).

I do not know if this started with a new version of AMSE or what.  It affects multiple computers.

I am baffled.  jay

[cid:image001.png@01D53E3E.42367FA0]

[cid:image003.jpg@01D53E3F.2C6C6260]

[cid:image007.jpg@01D53E3F.2C6C6260]

**Comment by xpouyat** [comment] 2019-07-19 20:09
Hi, 
I don't see the screen captures. Can you send them to my email : xpouyat @ microsoft.com ?
I am quite sure that the issue comes from a global filter (which is not displayed by the app because the method to display the filters crashes)

**Comment by jaycosentino** [comment] 2019-07-19 20:24
I see what you are saying.  When I try to refresh the global filters tab, I get the same unhandled exception message.  I do not think I want any global filters.  I do not think that I ever set any.  When I go to that tab and select Create a Global Filter, I know I have not seen this screen before.

How to clear them?

I am sending the pictures again with a copy to your Microsoft account.

[cid:image001.png@01D53E45.46B2DBD0]


[cid:image002.jpg@01D53E45.46B2DBD0]

[cid:image003.jpg@01D53E45.FB10B7A0]

**Comment by xpouyat** [comment] 2019-07-23 06:50
You should try Azure Shell to list the filters and delete one which causes the issue.
https://docs.microsoft.com/en-us/azure/media-services/latest/filters-dynamic-manifest-cli-howto
https://docs.microsoft.com/en-us/cli/azure/ams/account-filter?view=azure-cli-latest

Example:
az ams account-filter list -a myamsaccountname -g myresourcegroupname

To delete:
https://docs.microsoft.com/en-us/cli/azure/ams/account-filter?view=azure-cli-latest#az-ams-account-filter-delete

**Comment by jaycosentino** [comment] 2019-07-23 17:35
Thanks!  I am not a programmer, but I was able to install CLI and run az commands from PowerShell.  I use az login and I successfully login.  The Powershell displays my information.  Good so far.  I then am not sure of the ams command.  I have one media account (arclearn), one storage account tied to the media account (arclearn3), and a substantially unused storage account (arclearn2).

I use az ams account-filter list -a arclearn -g Default-Storage-WestUS and I get a message Parent resource 'arclearn' not found.  I tried changing to arclearn2 and to arclearn3 with the same result.

When I log into my Azure account and look at the dashboard and then my media account, it says the storage account arclearn3 has a resource group of Default-Storage-WestUS

I guess I do not understand the parameters.  Can you make a suggestion?

jay

**Comment by xpouyat** [comment] 2019-07-23 22:38
Hello, -a is used to set the AMS account (arclean) and -g the resource group of the AMS account. This resource group may be different from the storage account.
You can see the resource group name of the AMS account in the portal (overview of the AMS account)

**Comment by jaycosentino** [comment] 2019-07-24 15:49
Thanks!  Got it now.  You say that the “Object reference not set to an instance of an object” is definitely associated with a Global Filter.  You gave me a way to list out the filters.  See attached.  There is a long list of account filters and I have not created any of these.  No idea where these come from other than from you guys when the account or the AMSE application was installed.  I do not want to damage the account through my lack of knowledge.  How should I proceed?

Jay




[cid:image001.png@01D5420D.65910AB0]

**Comment by xpouyat** [comment] 2019-07-25 21:58
I am able to reproduce the problem with your first filter. I will keep you informed.

**Comment by xpouyat** [comment] 2020-06-13 19:48
Closing as there was a follow-up offline.

**Closed by xpouyat** 2020-06-13 19:48 UTC
