### ISSUE TITLE
Crash when exporting multiple assets to another AMS Account

### ISSUE THREAD

**Issue by cboileau** [Azure/Azure-Media-Services-Explorer#72] opened 2017-05-19 15:01 UTC
I'm able to export about 4 assets at a time without it crashing, any time I have more queued, AMS Explorer crashes.

Here is the information from Event Viewer

Application Error
Faulting application name: AMSExplorer.exe, version: 3.48.0.0, time stamp: 0x58bfd4c5
Faulting module name: KERNELBASE.dll, version: 10.0.14393.1198, time stamp: 0x5902845a
Exception code: 0xe0434352
Fault offset: 0x000da9f2
Faulting process id: 0x3804
Faulting application start time: 0x01d2d018af343551
Faulting application path: C:\Program Files (x86)\Microsoft Corporation\Azure Media Services Explorer\AMSExplorer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8ab1ef5a-0e8b-46b0-884b-eb4d341d9719
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime

Application: AMSExplorer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at System.Windows.Forms.Control.Invoke(System.Delegate)
   at AMSExplorer.Mainform.DoRefreshGridAssetV(Boolean)
   at AMSExplorer.Mainform+<ProcessExportAssetToAnotherAMSAccount>d__134.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

`

**Comment by xpouyat** [comment] 2017-05-19 16:14
Hi,
I am not able to reproduce the issue. Do you select any special option when doing the copy ? Do you have one Explorer window opened ? How many assets do you have in your account ? The crash seems to occur when the asset grid is refreshed and I try to understand the context.
- Xavier

**Comment by xpouyat** [comment] 2017-05-19 16:18
I think I was able to repro, using the deletion option when doing the copy

**Comment by xpouyat** [comment] 2017-05-20 17:42
I fix the issue. Fix will be in next public version. https://github.com/Azure/Azure-Media-Services-Explorer/commit/099598d2463c6885dcb08946e692f98a77250462
Thanks

**Closed by xpouyat** 2017-05-20 17:42 UTC
